{
 "title": "Experiment 1: SHAP values in different dataset sizes",
 "description": "This experiment should show the changes in shap values as dataset size get reduced to help us understand how SHAP values change independently from an poisoning attack.  Since in Federated Learning the size is drastically reduced due to the missing step of data aggregation. ",
 "time": { "from": "2022-05-27T06:49:51.979Z", "to": "2022-05-27T07:51:36.288Z" },
 "templating": {
  "list": [
   {
    "name": "datasize",
    "label": "datasize",
    "query": {
     "query": "label_values(client_accuracy, dataset_size)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Experiments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metadata of Experiments",
     "type": "table",
     "description": "poisoned data 1 due to a bug",
     "gridPos": { "h": 5, "w": 22, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "client_accuracy{experiment_id=\"0\", experiment_type=\"datasize_shap\"}",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    },
    {
     "title": "Accuracy",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_accuracy{experiment_type=\"datasize_shap\"})",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    },
    {
     "title": "Experiment Accuracy",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 10, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "client_accuracy{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", experiment_id=~\".*\"}",
       "legendFormat": "{{experiment_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Positive to negative shap values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"0\", source=\"0\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"0\", source=\"0\"}) "
    },
    {}
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 2 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"1\", source=\"1\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"1\", source=\"1\"}) "
    },
    {}
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"2\", source=\"2\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"2\", source=\"2\"}) "
    },
    {}
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 2 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"3\", source=\"3\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"3\", source=\"3\"}) "
    },
    {}
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"4\", source=\"4\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"300\", target=\"4\", source=\"4\"}) "
    },
    {}
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"5\", source=\"5\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"300\", target=\"5\", source=\"5\"}) "
    },
    {}
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"6\", source=\"6\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"6\", source=\"6\"}) "
    },
    {}
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"7\", source=\"7\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"300\", target=\"7\", source=\"7\"}) "
    },
    {}
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"8\", source=\"8\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"8\", source=\"8\"}) "
    }
   ]
  },
  {
   "title": "Positive and Negative SHAP values",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "avg by (target, source) (client_shap_pos{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"9\", source=\"9\"}) "
    },
    {
     "expr": "avg by (target, source) (client_shap_neg{experiment_type=\"datasize_shap\", dataset_size=\"$datasize\", target=\"9\", source=\"9\"}) "
    }
   ]
  },
  {
   "title": "Average Count SHAP Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average count of positive SHAP Values (0,0)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_shap_pos{experiment_type=\"datasize_shap\", target=\"0\", source=\"0\"}) ",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    },
    {
     "title": "Average Count of negative SHAP Values (0,0)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_shap_neg{experiment_type=\"datasize_shap\", target=\"0\", source=\"0\"}) ",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    },
    {
     "title": "Average Count of positive SHAP Values (0,9)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_shap_pos{experiment_type=\"datasize_shap\", target=\"0\", source=\"9\"}) ",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    },
    {
     "title": "Average Count of negative SHAP Values (0,9)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_shap_neg{experiment_type=\"datasize_shap\", target=\"0\", source=\"9\"}) ",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    },
    {
     "title": "Average count of positive SHAP Values (1,1)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_shap_pos{experiment_type=\"datasize_shap\", target=\"1\", source=\"1\"}) ",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    },
    {
     "title": "Average count of negative SHAP Values (1,1)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_shap_neg{experiment_type=\"datasize_shap\", target=\"1\", source=\"1\"}) ",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SHAP Mean",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average SHAP mean of Client 0 (0,0) by dataset_size ",
     "type": "bargauge",
     "description": "target = 0 and source = 0",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_shap_mean{experiment_type=\"datasize_shap\", target=\"0\", source=\"0\"}) ",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    },
    {
     "title": "Average SHAP mean of Client (0,9) by dataset_size ",
     "type": "bargauge",
     "description": "target = 0 and source = 0",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (dataset_size) (client_shap_mean{experiment_type=\"datasize_shap\", target=\"0\", source=\"9\"}) ",
       "legendFormat": "{{dataset_size}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Experiment 0",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accuracy",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "client_accuracy{experiment_id=\"0\",experiment_type=\"datasize_shap\"}",
       "legendFormat": "{{datasize}}"
      }
     ]
    },
    {
     "title": "Precision",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "client_precision{experiment_id=\"0\", experiment_type=\"datasize_shap\", dataset_size=\"$datasize\"}",
       "legendFormat": "{{target}}"
      }
     ]
    },
    {
     "title": "Recall",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "client_recall{experiment_id=\"0\", experiment_type=\"datasize_shap\", dataset_size=\"$datasize\"}",
       "legendFormat": "{{target}}"
      }
     ]
    }
   ]
  }
 ]
}